import { randomFullName } from './browser-identity'

export interface RegistrationConfig {
  // AWS
  oidcBase: string
  signinBase: string
  profileBase: string
  viewBase: string
  portalBase: string
  directoryId: string
  startURL: string

  // default value
  password: string
  fullName: string

  // runtime
  proxy: string
  /** Upstream transit agent (optional, used for agent chain): let the pair proxy(target agent) The connection is initiated via non-mainland transit */
  upstreamProxy: string
  /**
   * Strict proxy mode: After turning on any "proxy missing"/Agent chain failed/"Return environment variables" will immediately throw an error and terminate the registration.
   * Eliminate silent fallback to the real machine IP Direct connection. When the agent pool is enabled for batch registration, it is forcibly turned on by the front end.
   */
  strictProxy: boolean

  // MoEmail Configuration
  moEmailBaseURL: string
  moEmailAPIKey: string

  // Outlook model
  useOutlook: boolean
  outlookData: string

  // TempMail.Plus + Self-created domain name
  useTempMailPlus: boolean
  tempMailPlusEmail: string  // tempmail.plus Username (excluding @mailto.plus）
  tempMailPlusEpin: string
  tempMailPlusDomain: string // Self-created domain name

  // Proton Dot alias (webview To obtain codes from the official backdoor website, you need to log in within the app first. Proton）
  useProton: boolean
  protonEmail: string // Used for this registration Proton Email address (parent email or its dotted variant, generated by the frontend)

  // GPTmail (mail.chatgpt.org.uk) — Domain name mailbox code extraction supports two ways of playing:
  //   A. Private domain name direct payment:MX parse to GPTmail，inboxEmail Leave blank (please fill in if the private domain name requires a password to unlock) privatePassword）
  //   B. CF Email Routing Forward:inboxEmail Fill in a fixed GPTmail Mail
  useGptMail: boolean
  gptMailBaseURL: string      // Optional, default https://mail.chatgpt.org.uk;Private deployment can be changed
  gptMailInboxEmail: string   // Optional: Fill in = CF forwarding mode (all prefix@domain forward to this email); leave blank = Direct transfer of private domain names
  gptMailDomain: string       // Required: User’s own domain name pool, use spaces for multiple entries/comma
  gptMailPrefix: string       // Optional: fixed prefix, leave blank randomEmailPrefix() generate
  gptMailPrivatePassword: string  // Optional: Only private domain name mode is valid. exist GPTmail The password to set when setting up a private domain name

  // manual mode
  manualMode: boolean
}

export function genPassword(): string {
  const upper = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
  const lower = 'abcdefghijklmnopqrstuvwxyz'
  const digits = '0123456789'
  const special = '!@#$%^&*'

  let pw = ''
  for (let i = 0; i < 3; i++) pw += upper[Math.floor(Math.random() * upper.length)]
  for (let i = 0; i < 6; i++) pw += lower[Math.floor(Math.random() * lower.length)]
  for (let i = 0; i < 3; i++) pw += digits[Math.floor(Math.random() * digits.length)]
  for (let i = 0; i < 2; i++) pw += special[Math.floor(Math.random() * special.length)]

  const arr = pw.split('')
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[arr[i], arr[j]] = [arr[j], arr[i]]
  }
  return arr.join('')
}

export function newConfig(overrides?: Partial<RegistrationConfig>): RegistrationConfig {
  return {
    oidcBase: 'https://oidc.us-east-1.amazonaws.com',
    signinBase: 'https://us-east-1.signin.aws',
    profileBase: 'https://profile.aws.amazon.com',
    viewBase: 'https://view.awsapps.com',
    portalBase: 'https://portal.sso.us-east-1.amazonaws.com',
    directoryId: 'd-9067642ac7',
    startURL: 'https://view.awsapps.com/start',
    password: genPassword(),
    fullName: randomFullName(),
    proxy: '',
    upstreamProxy: '',
    strictProxy: false,
    moEmailBaseURL: '',
    moEmailAPIKey: '',
    useOutlook: false,
    outlookData: '',
    useTempMailPlus: false,
    tempMailPlusEmail: '',
    tempMailPlusEpin: '',
    tempMailPlusDomain: '',
    useProton: false,
    protonEmail: '',
    useGptMail: false,
    gptMailBaseURL: '',
    gptMailInboxEmail: '',
    gptMailDomain: '',
    gptMailPrefix: '',
    gptMailPrivatePassword: '',
    manualMode: false,
    ...overrides
  }
}
